### ISSUE TITLE
别忘了内存释放功能

### ISSUE THREAD

**Issue by LYYZZ** [LunacyZeus/palworld-chan#1]
别忘了内存释放功能，这在官方没修复前是刚需。

**Comment by LunacyZeus** [comment]
https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix 你可能需要看看这个项目....非官方的服务端,已经解决这问题了.
windows的内存释放可以通过压榨内存触发系统清理来实现,linux的目前没找到好办法 正在研究中

**Comment by xiaomait** [comment]
期待作者的更新
