### ISSUE TITLE
大佬，未实装是还没写这功能吗？

### ISSUE THREAD

**Issue by zhangxxyz** [LunacyZeus/palworld-chan#12]
还有，我点RCON，一直是链接信息不能为空

**Comment by LunacyZeus** [comment]
需要去设置界面设置RCON才有，在设置里面，你设置了连接地址端口密码后，就可以用了

**Comment by zhangxxyz** [comment]
配置好以后，进去看到最后的一个用户，是缺失的数据，你们会有这种情况吗，还是只有我的电脑才有这情况，我看了下，在以后的steamid只有一部分

**Comment by zhangxxyz** [comment]
大佬，先弄白名单功能吧，现在恶心的人太多了，上来就炸服

**Comment by LunacyZeus** [comment]
这个是官方服务端解析的bug，目前暂时不知道怎么解决，我是准备本地缓存下，这个服务端不支持白名单功能吧，好像只有黑名单

**Comment by zhangxxyz** [comment]
就是本地保存个文档，是白名单，获取在线人员，不是白名单内部的都踢掉，我用python写了个，但是因为RCON的问题，导致最后进入的始终获取不全，就很麻烦。这游戏bug太多了。

**Comment by zhangxxyz** [comment]
我看你这功能全。原来你也获取不了最后的啊，我以为我代码问题，找了半天

**Comment by LunacyZeus** [comment]
基于steamid/name搞个白名单就行了吧，这东西一直请求不知道服务端那边会不会有bug，你都用白名单了为啥不设置机器密码

**Comment by LunacyZeus** [comment]
已解决以上问题
