### ISSUE TITLE
在线用户无法踢出与封禁，请问是还没有实装吗

### ISSUE THREAD

**Issue by BILIBlLl** [LunacyZeus/palworld-chan#18]
![image](https://github.com/LunacyZeus/palworld-chan/assets/30714550/7d2cfd86-4e03-405a-8327-b4914324a072)

**Comment by LunacyZeus** [comment]
新版显示异常已经修正 这个是由于rcon返回最后一个用户为空导致的 我这边做了一个用户的本地缓存等下次获取到后就持久保存了
踢出和封禁 前端还有点bug 尽快解决中
