### ISSUE TITLE
 net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by hiyoit** [LunacyZeus/palworld-chan#33]
是不是还有跨域问题没解决？服务端部署，其他端打开会遇到报错：
https://px.effirst.com/api/v1/jconfig?wpk-header=app%3Dfqy8bgb3-is7w88xm%26tm%3D1707291256%26ud%3Dded7871d-3018-467f-3b22-0efab2d51807%26sver%3D%26sign%3Dc41e43c828c16c16a6eb1c9c1e68e8ce net::ERR_SSL_PROTOCOL_ERROR

**Comment by LunacyZeus** [comment]
这接口不是我的吧。。。

**Comment by LunacyZeus** [comment]
如果要绑定域名，推荐用nginx套一层
