### ISSUE TITLE
0.05 版本启动问题

### ISSUE THREAD

**Issue by Chris-JLin** [LunacyZeus/palworld-chan#36]
0.05 版本启动后，web端一直转圈圈，加载不出来登陆界面。

**Comment by LunacyZeus** [comment]
方便发一下F12看看浏览器network抓包吗

**Comment by LunacyZeus** [comment]
感谢指出 应该是github自动打包有问题 我这边马上处理

**Comment by Chris-JLin** [comment]
![微信截图_20240207234604](https://github.com/LunacyZeus/palworld-chan/assets/156224841/29ec9a9c-139a-49e9-bb8c-3ad07a499db6)

**Comment by Chris-JLin** [comment]
0.051 已解决此问题 💯

**Comment by LunacyZeus** [comment]
感谢issues
