### ISSUE TITLE
如何启动UI界面

### ISSUE THREAD

**Issue by xiaomait** [LunacyZeus/palworld-chan#4]
是否有交流群，小白该如何启动UI界面
`
root@ctser834066146291:~# ./palworld_chan_amd64_linux ui
`
`
Error: Wails applications will not build without the correct build tags.
`

**Comment by LunacyZeus** [comment]
稍等 正在更新相关文档和视频

**Comment by LunacyZeus** [comment]
palworld-chan api
最新的二进制文件用这个命令

**Comment by zhangxxyz** [comment]
win的.bat点击不行啊

**Comment by zhangxxyz** [comment]
@palworld_chan.exe 这个在哪里啊

**Comment by xiaomait** [comment]
默认的账户密码是什么呢

**Comment by xiaomait** [comment]
已经找到感谢作者
![Uploading WX20240131-202450.png…]()

**Comment by xiaomait** [comment]
![WX20240131-202450](https://github.com/LunacyZeus/palworld-chan/assets/97210675/c4729518-3d63-4b78-8ed9-891c9232248a)
已经找到感谢作者

**Comment by LunacyZeus** [comment]
这方面还没开发 等等我加入到持久层或者基于命令行重置就行 目前自动备份 重启 发送消息 在线用户 测试稳定了 其他的我还在更新

**Comment by xiaomait** [comment]
> 还没开发 等等我加入到持久层或者基于命令行重置就

现在启动之后，都写着未实装，这是怎么回事

**Comment by LunacyZeus** [comment]
linux还是windows?我看看 我测的是windows 工具页面就两个模块没接入 其他的都是能用的

**Comment by LunacyZeus** [comment]
等我发布releases 再看看吧~

**Comment by xiaomait** [comment]
期待更完善的程序

**Comment by nvcooc** [comment]
有PalServer运行久了，rcon连接超时的情况么

**Comment by zhangxxyz** [comment]
一直是密码不正确，即使我按照启动行里的密码启动。win10

**Comment by LunacyZeus** [comment]
新版教程在readme中，可以命令行设置密码了，启动也是一样的。
