### ISSUE TITLE
进入目录之后显示sudo: palworld-chan：找不到命令

### ISSUE THREAD

**Issue by 26821300** [LunacyZeus/palworld-chan#9]
Ubuntu22.04 下进入脚本目录后按照教程输入palworld-chan api 之后，显示sudo: palworld-chan：找不到命令

**Comment by 26821300** [comment]
已解决，直接./palworld_chan_api_amd64_linux  api执行

**Comment by LunacyZeus** [comment]
最新的可以下载看看，我这里测试是可以用的。
